# Configuration de base
spring.application.name=Tickup-notify
server.port=9002
## Mail config pparams
#spring.mail.host=sandbox.smtp.mailtrap.io
#spring.mail.port=2525
#spring.mail.username=b7e3ac1cde7979
#spring.mail.password=bf088526eff735
#spring.mail.protocol=smtp
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true

# Gmail config pparams
# Gmail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=samuelkebe09.skb@gmail.com
spring.mail.password=jaow mkvm bavo fsrw

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# corrige l'erreur PKIX
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2

# expéditeur
mail.sender.email=no-reply@tickup.com
mail.sender.name=Tickup

logging.level.org.springframework.mail=DEBUG
logging.level.org.eclipse.angus.mail=DEBUG
